### ISSUE TITLE
New papers on table recognition

### ISSUE THREAD

**Issue by ShengYun-Peng** [zacharywhitley/awesome-ocr#4]
Hi @zacharywhitley, thanks for the awesome repo and dedication in compiling this curated reading list! We have a series of three new papers on table recognition available at https://github.com/poloclub/unitable. We would be grateful if you could add them to the list.

**Comment by zacharywhitley** [comment]
I'd be happy to. Thanks for the link and the positive feedback!

**Comment by zacharywhitley** [comment]
Done.
